services:
    huellitas-backend:
        build:
            context: ./backend-huellitas
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - huellitas-network

networks:
    huellitas-network:
        driver: bridge
